- name: Ensure /srv directory exists
  become: true
  file:
    path: /srv
    state: directory
    mode: '0755'
    owner: admin
    group: admin

- name: Ensure /srv/caro directory exists
  become: true
  file:
    path: /srv/caro
    state: directory
    mode: "{{ user_dirs_permissions }}"
    owner: caro
    group: caro

- name: Ensure /srv/quentin directory exists
  become: true
  file:
    path: /srv/quentin
    state: directory
    mode: "{{ user_dirs_permissions }}"
    owner: quentin
    group: quentin
