---
- name: Find vhost templates locally
  delegate_to: localhost
  find:
    paths: "resources/caro/websites/vhosts"
    patterns: "*.conf.j2"
  register: vhost_templates
- name: Deduce DNS names
  ansible.builtin.set_fact:
    dns_names: >-
      {{
          vhost_templates.files
            | map(attribute='path')
            | map('basename')
            | map('regex_replace', '\.conf\.j2$', '')
            | list
      }}
- name: Set websites fact
  ansible.builtin.set_fact:
    caro_websites: >-
      {{ (websites | default([])) + [{
        'dns_name': item,
        'name': item | regex_replace('\.', '-'),
        'volume_name': 'caro-websites-' ~ (item | regex_replace('\.', '-'))
      }] }}
  with_items: "{{ dns_names }}"
