- name: Deploy public Caddy reverse proxy
  become_user: ansible
  hosts: main
  vars:
    public_proxy_root: /srv/public-proxy

  tasks:
    - name: Ensure /srv/public-proxy directories exists
      become: true
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        owner: ansible
        group: ansible
      loop:
        - "{{ public_proxy_root }}"
        - "{{ public_proxy_root }}/config"
        - "{{ public_proxy_root }}/data"

    - name: Deploy Caddyfile
      template:
        src: "resources/public-proxy/Caddyfile.j2"
        dest: "{{ public_proxy_root }}/Caddyfile"
        mode: '0644'
      notify: Restart caddy

    - name: Deploy compose.yml for Caddy
      template:
        src: "resources/public-proxy/compose.yml.j2"
        dest: "{{ public_proxy_root }}/compose.yml"
        mode: '0644'
      notify: Restart caddy

    - name: Start services with docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ public_proxy_root }}"
        state: present

  handlers:
    - name: Restart caddy
      community.docker.docker_compose_v2:
        project_src: "{{ public_proxy_root }}"
        state: restarted
