- name: Deploy per-user SFTP containers
  hosts: main
  vars:
    sftp_users:

  tasks:
    - name: List Caro websites
      include_tasks: ./tasks/list-caro-websites.yaml
    - name: Set sftp_users fact
      set_fact: 
        # php-nginx docker image runs with user 1000, so sftp should create files with this ownership
        sftp_users: >-
          {{[
            {
              'name': 'caro',
              'uid': 1000,
              'gid': 1000,
              'port': 2222,
              'root_folder': '/srv/caro/sftp-caro',
              'websites': caro_websites
            },
            { 
              'name': 'quentin',
              'uid': 1000,
              'gid': 1000,
              'port': 2223,
              'root_folder': '/srv/quentin/sftp-quentin',
              'websites': caro_websites
                          | selectattr('dns_name', 'match', 'bonnet.software')
                          | list
            }
          ]}}

    - name: Deploy SFTP containers
      loop: "{{ sftp_users }}"
      loop_control:
        loop_var: sftp_user
      include_tasks: ./tasks/deploy-sftp-user-instance.yml
