- name: Setup users with SSH keys
  hosts: main
  become: true
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/vps-root
    users:
      - name: quentin
        ssh_key: "{{ lookup('file', 'resources/keys/quentin.pub') }}"
      - name: caro
        ssh_key: "{{ lookup('file', 'resources/keys/caro.pub') }}"
      - name: ansible
        ssh_key: "{{ lookup('file', 'resources/keys/ansible.pub') }}"

  tasks:
    - name: Ensure users exist
      user:
        name: "{{ item.name }}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ item.name }}/.ssh"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Add authorized_keys
      copy:
        content: "{{ item.ssh_key }}"
        dest: "/home/{{ item.name }}/.ssh/authorized_keys"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: '0600'
      loop: "{{ users }}"
      notify: Restart sshd

  handlers:
    - name: Restart sshd
      service:
        name: sshd
        state: restarted

